name: CD for harshanu website
on: push
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 23 -t rsa $HETZNER_STORAGE_HOST >> ~/.ssh/known_hosts

      - name: Deploy code to storage box
        run: |
          scp -P 23 -r $(pwd) $HETZNER_STORAGE_USER@$HETZNER_STORAGE_HOST:$REMOTE_WEBSITE_PATH
