name: CD for harshanu website
on: push
jobs:
  deploy:
    #runs-on: self-hosted
    #steps:
    #  - name: Git checkout
    #    uses: actions/checkout@v2

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 u362339.your-storagebox.de >> ~/.ssh/known_hosts

      - name: Deploy code to storage box
        run: |
          scp -r ./ u362339-sub2@u362339.your-storagebox.de:~/harshanu/_work/harshavmb.github.io/harshavmb.github.io/
