name: CD for harshanu website
on: push
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 23 -t rsa ${{ env.HETZNER_STORAGE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code to storage box
        run: |
          scp -P 23 -r $(pwd) ${{ env.HETZNER_STORAGE_USER }}@${{ env.HETZNER_STORAGE_HOST }}:${{ env.REMOTE_WEBSITE_PATH }}
